# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Gerador(object):
    def setupUi(self, Gerador):
        Gerador.setObjectName("Gerador")
        Gerador.resize(485, 552)
        Gerador.setStyleSheet("")
        self.num1 = QtWidgets.QLabel(Gerador)
        self.num1.setGeometry(QtCore.QRect(10, 350, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(32)
        self.num1.setFont(font)
        self.num1.setStyleSheet("border-radius : 35;\n"
"border : 2px solid black;\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid;\n"
"border-color:#ffc600;")
        self.num1.setText("")
        self.num1.setAlignment(QtCore.Qt.AlignCenter)
        self.num1.setObjectName("num1")
        self.num2 = QtWidgets.QLabel(Gerador)
        self.num2.setGeometry(QtCore.QRect(90, 350, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(32)
        self.num2.setFont(font)
        self.num2.setStyleSheet("border-radius : 35;\n"
"border : 2px solid black;\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid;\n"
"border-color:#ffc600;")
        self.num2.setText("")
        self.num2.setAlignment(QtCore.Qt.AlignCenter)
        self.num2.setObjectName("num2")
        self.num3 = QtWidgets.QLabel(Gerador)
        self.num3.setGeometry(QtCore.QRect(170, 350, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(32)
        self.num3.setFont(font)
        self.num3.setStyleSheet("border-radius : 35;\n"
"border : 2px solid black;\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid;\n"
"border-color:#ffc600;")
        self.num3.setText("")
        self.num3.setAlignment(QtCore.Qt.AlignCenter)
        self.num3.setObjectName("num3")
        self.num4 = QtWidgets.QLabel(Gerador)
        self.num4.setGeometry(QtCore.QRect(250, 350, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(32)
        self.num4.setFont(font)
        self.num4.setStyleSheet("border-radius : 35;\n"
"border : 2px solid black;\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid;\n"
"border-color:#ffc600;")
        self.num4.setText("")
        self.num4.setAlignment(QtCore.Qt.AlignCenter)
        self.num4.setObjectName("num4")
        self.num5 = QtWidgets.QLabel(Gerador)
        self.num5.setGeometry(QtCore.QRect(330, 350, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(32)
        self.num5.setFont(font)
        self.num5.setStyleSheet("border-radius : 35;\n"
"border : 2px solid black;\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid;\n"
"border-color:#ffc600;")
        self.num5.setText("")
        self.num5.setAlignment(QtCore.Qt.AlignCenter)
        self.num5.setObjectName("num5")
        self.num6 = QtWidgets.QLabel(Gerador)
        self.num6.setGeometry(QtCore.QRect(410, 350, 70, 70))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(32)
        self.num6.setFont(font)
        self.num6.setStyleSheet("border-radius : 35;\n"
"border : 2px solid black;\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"border: 2px solid;\n"
"border-color:#ffc600;")
        self.num6.setText("")
        self.num6.setAlignment(QtCore.Qt.AlignCenter)
        self.num6.setObjectName("num6")
        self.lbl_sorte = QtWidgets.QLabel(Gerador)
        self.lbl_sorte.setGeometry(QtCore.QRect(10, 120, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lbl_sorte.setFont(font)
        self.lbl_sorte.setStyleSheet("color: rgb(255, 226, 5);")
        self.lbl_sorte.setObjectName("lbl_sorte")
        self.sorte1 = QtWidgets.QLineEdit(Gerador)
        self.sorte1.setGeometry(QtCore.QRect(300, 110, 56, 56))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(26)
        self.sorte1.setFont(font)
        self.sorte1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid;\n"
"border-color:#ffc600;\n"
"border-radius: 28;\n"
"")
        self.sorte1.setText("")
        self.sorte1.setAlignment(QtCore.Qt.AlignCenter)
        self.sorte1.setObjectName("sorte1")
        self.sorte2 = QtWidgets.QLineEdit(Gerador)
        self.sorte2.setGeometry(QtCore.QRect(360, 110, 56, 56))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(26)
        self.sorte2.setFont(font)
        self.sorte2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 28;\n"
"border: 2px solid;\n"
"border-color:#ffc600;")
        self.sorte2.setText("")
        self.sorte2.setAlignment(QtCore.Qt.AlignCenter)
        self.sorte2.setObjectName("sorte2")
        self.sorte3 = QtWidgets.QLineEdit(Gerador)
        self.sorte3.setGeometry(QtCore.QRect(420, 110, 56, 56))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(26)
        self.sorte3.setFont(font)
        self.sorte3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 28;\n"
"border: 2px solid;\n"
"border-color:#ffc600;")
        self.sorte3.setText("")
        self.sorte3.setAlignment(QtCore.Qt.AlignCenter)
        self.sorte3.setObjectName("sorte3")
        self.btn_gerar = QtWidgets.QPushButton(Gerador)
        self.btn_gerar.setGeometry(QtCore.QRect(175, 480, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(24)
        self.btn_gerar.setFont(font)
        self.btn_gerar.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 0, 4);\n"
"border-radius: 10px;\n"
"color: rgb(255, 226, 5);\n"
"border: 2px solid;\n"
"border-color:#ffc600;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 226, 5);\n"
"color: rgb(255, 0, 4);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(2, 18, 255);\n"
"}")
        self.btn_gerar.setObjectName("btn_gerar")
        self.navbar = QtWidgets.QWidget(Gerador)
        self.navbar.setGeometry(QtCore.QRect(0, 0, 491, 91))
        self.navbar.setStyleSheet("color: #ffc600;")
        self.navbar.setObjectName("navbar")
        self.lbl_gerador = QtWidgets.QLabel(self.navbar)
        self.lbl_gerador.setGeometry(QtCore.QRect(20, 20, 451, 61))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_gerador.setFont(font)
        self.lbl_gerador.setObjectName("lbl_gerador")
        self.label = QtWidgets.QLabel(Gerador)
        self.label.setGeometry(QtCore.QRect(150, 220, 265, 71))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(34)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 226, 5);")
        self.label.setObjectName("label")
        self.BG = QtWidgets.QWidget(Gerador)
        self.BG.setGeometry(QtCore.QRect(0, 0, 501, 575))
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        self.BG.setFont(font)
        self.BG.setStyleSheet("background-image: url(:/image/bg_lot.jpg);")
        self.BG.setObjectName("BG")
        self.BG.raise_()
        self.num1.raise_()
        self.num2.raise_()
        self.num3.raise_()
        self.num4.raise_()
        self.num5.raise_()
        self.num6.raise_()
        self.lbl_sorte.raise_()
        self.sorte1.raise_()
        self.sorte2.raise_()
        self.sorte3.raise_()
        self.btn_gerar.raise_()
        self.navbar.raise_()
        self.label.raise_()

        self.retranslateUi(Gerador)
        QtCore.QMetaObject.connectSlotsByName(Gerador)

    def retranslateUi(self, Gerador):
        _translate = QtCore.QCoreApplication.translate
        Gerador.setWindowTitle(_translate("Gerador", "Gerador de Sena"))
        self.lbl_sorte.setText(_translate("Gerador", "Tem algum número da sorte?"))
        self.btn_gerar.setText(_translate("Gerador", "GERAR"))
        self.lbl_gerador.setText(_translate("Gerador", "GERADOR DE NÚMEROS"))
        self.label.setText(_translate("Gerador", "BOA SORTE!!!"))
import files_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Gerador = QtWidgets.QWidget()
    ui = Ui_Gerador()
    ui.setupUi(Gerador)
    Gerador.show()
    sys.exit(app.exec_())
